[default]
# Don't correct the following words:
extend-ignore-words-re = ["ASSER", "Tne", "ba", "BA"]

[files]
# completely exclude those files from consideration:
extend-exclude = ["test/supp/*.supp"]
